
#test

[general]
data_path = "data/explicit_latents/12-02-9.h5"
ckpt_path = "checkpoints/implicit_latents/12-08-3.ckpt"

[train]
batch_size = 128
num_epochs = 750
num_workers = 16

[train.opt]
learning_rate = 0.0004
warmup_epochs= 0
decay_epochs = 250
decay_rate = 0.5

[dynamics]
latent_dim = 5
edge_dim = 64
latent_edge_dim = 6

[dynamics.weights]
prediction = 1
disentanglement = 1
