# Default implicit dynamics configuration
type = "implicit_dynamics"

[data]
skip_explicit_perts = false

[model]
explicit_dim = 3
latent_dim = 5
edge_dim = 64
latent_edge_dim = 64
t_past = 4

[train]
batch_size = 128
epochs = 500
ckpt_rate = 100
t_future = 4

[train.opt]
lr = 0.0004
lr_warmup_epochs= 0
lr_decay_epochs = 200
lr_decay_rate = 0.5
weight_decay = 0.0

[train.weights]
prediction = 1
disentanglement = 0
